fix out-of-bounds access in uvc_yuyv2bgr()
libuvc/libuvc pull request #211
Opened 2022-03-09 05:20 UTC by r00t-

with my camera, using the example program, i see a very high rate of crashes in uvc_yuyv2bgr().

i tracked this to reading beyond the end of the input buffer.
the macro makes this hard to debug, but adding a read of the to-be read source data before the macro call made it obvious:
```
+       uint8_t x=*pyuv;
     IYUYV2BGR_8(pyuv, pbgr);
```

looking at the code of the function, it seems to make a generous assumption on the size of the yuv input buffer matching the size of the bgr output buffer.
(also, it iterates over the buffer 

the crashes stopped when i had it iterate over the size of the input buffer instead of the output buffer.
(it's possible that the actual error is somewhere else, i.e. the buffer size calculation, i did not look further.)

2022-03-09 15:25 UTC, r00t- commented
actually the code should be checking the limits of both buffers - it  could also happen that the input buffer is larger than the geometry would require, which would lead to oob on the output.

not sure what the best approach is...
with the steps-size differing in both buffers... maintain two counters? do a multiplication+addition inside the loop? or do some math before the loop to establish/check the limits?

2022-03-09 23:50 UTC, r00t- commented
updated code with improvements.
- check input buffer is large enough for geometry (strangely that was previously done for the output buffer, but not for the input buffer?!)
- check for both buffer's end while processing.)
actually this is redundant now.
and should be applied to all the conversion routines, not just rgb/bgr.

waiting for feedback.

2022-03-10 15:01 UTC, waddlesplash commented
I'm not so sure about this. Some of the computations in here look a bit strange, and I can't say I actually understood this code before...

2022-03-10 17:26 UTC, r00t- commented
@waddlesplash:
the code (ignoring the specific content of the macros) is quite simple,
it iterates over two buffers, copying data from one to the other (with some math done on it).
the bug is in how it calculates the size of the target buffer from the image geometry stored in the source buffer,
and then iterates over the size of the target buffer, simply assuming that the source buffer contains a matching amount of data, which (as demonstrated by the crashes i'm seeing) is not actually enforced anywhere.

this should be fixed so it does not crash in such cases.
(the causes of the buffer being too small are separate bugs.)

the MR has two redundant fixes right now,
one is to verify the source buffer contains enough data to match the image geometry,
the second is to adjust the iteration to avoid out-of-bounds access on the buffer.

as for the calculation of the buffer ends,
the loop is unusual in how it iterates over the buffer in large steps (2*8 and 3*8 bytes),
so it's we actually need to stop iterating 2*3/3*8 bytes before the end of the buffer to avoid access beyond the end.
(and also there's no guarantee anywhere that the buffer contains a multiple of 2*8 bytes!
 i.e. if the input buffer buffer is smaller than 16 bytes, no single conversion could be done.)
 `- 2 * 8 + 1` seems right. if the buffer was exactly 16 bytes, that puts the end of the buffer at start+1, allowing exactly one iteration. (`while (pyuv < pyuv_end)`)

2022-03-15 18:45 UTC, waddlesplash commented
It would likely be better to re-structure the code so that such "magic number" calculations aren't needed. Or at least add some careful comments...

2022-09-22 19:26 UTC, damijans requested changes
I was facing the same issue as you. In my case the the CPU was overloaded and did not manage to collect complete image from the camera. In this way frame->data_bytes was set in _uvc_populate_frame() function to the number of received bytes and also the memory buffer was allocated to that size.  Unfortunately none of conversion function actually checks the size of allocated buffer so conversion could go over the allocated memory.

In my case I implement exactly the same solution (without knowing about your ticket) except checking (pyuv < pyuv_end) is redundant.

2026-09-03 04:52 UTC, drinkcat commented
Tricky, because `data_bytes` doesn't necessarily match the actual image size (it can be larger, even with the added if check), tried to rework this here: https://github.com/drinkcat/libuvc/pull/12 .

But yeah, we absolutely need unit tests.

2026-09-05 03:09 UTC, drinkcat commented
I picked this fix, then modified it a bit more to simplify it, and added unit tests here: #309 . Reviews would be very welcome! Thanks!

2026-09-05 03:09 UTC, closed without merging